### ISSUE TITLE
Level returning as -1

### ISSUE THREAD

**Issue by JamsRepos** [Summer-16/CSGO-NonPrimePlayerKicker#1]
Any reason why https://github.com/Summer-16/CSGO-NonPrimePlayerKicker/blob/master/NonPrimeKicker.sp#L26 is sometimes -1?

**Comment by Summer-16** [comment]
Reason :- GetPlayerResourceEntity() will return -1 if resource entity is not found ref(https://sm.alliedmods.net/new-api/sdktools/GetPlayerResourceEntity).

I have also seen some cases when it returned -1 with previous code when I was checking if the player is in-game so I thought it may be giving -1 bcoz player selected the team bud didn't enter the game that's why I updated the code and used, a plugin with it autojoin which make the player instantly select the team once connected (so far not got any reports but still waiting for a response from community players)

give it a try with that plugin(https://forums.alliedmods.net/showthread.php?p=2493575). If you need an edited version of this plugin which does not respawn player after team join let me know

Suggestion for code optimization are Welcomed

**Comment by JamsRepos** [comment]
I'm using a native to call when to check, it seems pretty much everyone returns as -1. Is this due to the right event not being called? 

Ideally I want it to be done when that native is called as that's when our VIP flags are set.

```
public void tVip_OnClientLoadedPost(int iClient) // This forward runs later than OnPostAdminCheck (So we don't actually kick before tVIP had a chance to set his flags.)
{
	if(IsFakeClient(iClient)) // Client is a bot, ignore him.
		return;
    
	// Client is vip
	if(CheckCommandAccess(iClient, "sm_amIVip", (1 << 19), true) || CheckCommandAccess(iClient, "sm_amIVip", (1 << 20), true))
		return;

	int playerlevel = GetEntProp(GetPlayerResourceEntity(), Prop_Send, "m_nPersonaDataPublicLevel", _, iClient);

	if (CheckCommandAccess(iClient, "BypassPremiumCheck", ADMFLAG_GENERIC, true))
		return;
	else if (playerlevel > 2)
		return;
	else if (playerlevel >= 0 && playerlevel <= 2)
		KickClient(iClient, "You need to be a minimum of Level 2 to play on this server");
	else
		LogError("%N is level %d and should be kicked.", iClient, playerlevel);
}
```

**Comment by Summer-16** [comment]
Oh you are using a different event then what I used, I already had this issue in my early compiles, I used on post admin check and it always returned -1 in that then I made a little console command and get to know that it was running fine when I pass that command while I am in-game so I decided to change my event and current event which is team join is working well for me.

So it may be due to the event, try using a different event 

my understanding(GetEntProp(GetPlayerResourceEntity(), Prop_Send, "m_nPersonaDataPublicLevel", _, iClient) this will only work once player is inside the game)

**Comment by JamsRepos** [comment]
Ah, so I'm possibly calling too early? As I tried with on team but like you say, some of my servers do indeed force them to a team so they're forced to a team because that native is called sometimes too late.

**Comment by Summer-16** [comment]
yes calling too early seems to be the issue to me.
